server:
  port: 8123


#spring:
#  redis:
#    database: 9
#    host: 127.0.0.1
#    port: 6379
#
#

logging:
  level:
    com.github.huifer.view.redis: debug


view:
  redis:
    login_name: admin
    password: admin